/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.InputStream;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class App {

    public static class Record {
        public String label;
        public BigDecimal value;
        public int rank;
        public int order;

        @Override
        public String toString() {
            return String.format("'%s' $%5.2f #%2d%2d", label, value, rank, order);
        }
    }

    public static void main(String[] args) throws Exception {
        // Corresponds to the file 'out.10n' - A collection of Records as Ion binary top-level values
        InputStream binaryIon = Producer.binaryIonRecordStream();
        // Corresponds to the file 'out.ion' - A collection of Records as Ion text top-level values
        InputStream textIon = Producer.textIonRecordStream();

        // Your task is to populate `records` by reading Ion data from one of the above streams.
        // You can use the internet, look for sample code or documentation.
        // You can test your code by:
        // * running `main` from your IDE
        // * or by executing the app via `./gradlew run` from the project root
        List<Record> records = new ArrayList<>();

        Consumer.processRecords(records);
    }

}
