/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    val autoValueVersion = "1.10.1"
    compileOnly("com.google.auto.value:auto-value-annotations:${autoValueVersion}")
    annotationProcessor("com.google.auto.value:auto-value:${autoValueVersion}")

    implementation("com.amazon.ion:ion-java:1.9.5")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-ion:2.14.2")
}

application {
    // Define the main class for the application.
    mainClass.set("App")
}


// Necessary to allow exception stack traces to be visible if some error is made in the app
tasks {
    withType<JavaExec> {
        setIgnoreExitValue(true)
    }
}

// The application plugin's run task changes the working directory :(
// See: https://github.com/gradle/gradle/issues/6074
tasks.run.get().workingDir = rootDir
