/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ion.java.hello.world;

import java.math.BigDecimal;
import java.util.List;

public class App {
    public static class Record {
        public String label;
        public BigDecimal value;
        public int rank;
        public int order;

        @Override
        public String toString() {
            return String.format("'%s' $%5.2f #%2d%2d", label, value, rank, order);
        }
    }

    public static void main(String[] args) throws Exception {
        // Files available:
        // 'out.ion' - A collection of Records as Ion text top-level values
        // 'out.10n' - A collection of Records as Ion binary top-level values
        //
        // Your task is to populate `records` by reading Ion data from one of the above files.
        // Could start with e.g. InputStream in = new FileInputStream("out.10n") ...
        // You can use the internet, look for sample code or documentation.
        // Test your code by running `main`, or by executing the app via `./gradlew run` from the project root.
        List<Record> records = null;

        Lib.processRecords(records);
    }

}
